name: 3D-Antarctic-maps
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - gmt=6.5.0
  - pygmt=0.12.0
  - jupyterlab=3.4.0
  - jupyter-offlinenotebook=0.2.2
  # Optional dependencies
  
